[workspace.lints.rust]
unsafe_code = "forbid"
# unused = "allow" # For experimental dev

[workspace]
resolver = "2"
members = [
    # -- Application Libraries
    "crates/libs",

    # -- Application Services
    "crates/services",

    # -- Tools
    "crates/tools",

]
